name: Build and Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Get Go version from go.mod
        id: get_go_version
        run: |
          # Extract the Go version from the "toolchain" line in go.mod (e.g. "toolchain go1.23.2" becomes "1.23.2")
          go_version=$(grep '^toolchain' go.mod | awk '{print $2}' | sed 's/go//')
          echo "go_version=$go_version" >> $GITHUB_OUTPUT

      - name: Set up Go
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a
        with:
          go-version: ${{ steps.get_go_version.outputs.go_version }}

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y libbpf-dev
          sudo apt install -y libseccomp-dev

      - name: Build and Test
        run: |
          make build-gh

      - name: Upload Artifact
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b
        with:
          name: harpoon
          path: bin/harpoon

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16
        with:
          name: harpoon
          path: ./
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@e7a8f85e1c67a31e6ed99a94b41bd0b71bbee6b8
        with:
          files: |
            harpoon
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-push-docker:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744

      - name: Log in to Docker Hub
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: make build-docker

      - name: Push Docker image to Docker Hub
        run: make push-docker

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image (GHCR)
        run: IMAGE_NAME="ghcr.io/alegrey91/harpoon" make build-docker
  
      - name: Push Docker image to GHCR
        run: IMAGE_NAME="ghcr.io/alegrey91/harpoon" make push-docker
